name: Docker Nightly Push CI

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }} 
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build and push multi-arch images
      run: |
        docker buildx create --use
        docker buildx build --platform linux/amd64,linux/arm64 -t teskalabs/bspump:nightly --file ./master/py37/bspump.Dockerfile --push .
        docker buildx build --platform linux/amd64,linux/arm64 -t teskalabs/bspump:nightly-py38 --file ./master/py38/bspump.Dockerfile --push .
        docker buildx build --platform linux/amd64,linux/arm64 -t teskalabs/bspump:nightly-py311 --file ./master/py311/bspump.Dockerfile --push .
